### ISSUE TITLE
Deprecate by using thenify

### ISSUE THREAD

**Issue by ruimarinho** [thenables/bcrypt-then#1]
@jonathanong any reason not to recommend people using `thenify` for this purpose?

**Comment by jonathanong** [comment]
i have a dream that one day we can just replace `require('bcrypt-then')` with `require('bcrypt')` instead of replacing `thenify(require('bcrypt'))`. hahahaha

**Comment by ruimarinho** [comment]
Or a replace :) who knows, one can dream.

```js
/require\('thenify'\)\(require\('(\w+)'\)\)/, 'require(\'$1\')'
```
